spring:
  devtools:
    livereload:
      enabled: true
  freemarker:
    cache: false    #    실서버 배포시에는 이 옵션을 개발서버와 실서버용으로 분리시켜야 한다. 템플릿을 캐시하지 않으면 서버 터지는걸 볼 수 있다. https://jojoldu.tistory.com/48
  thymeleaf:
    cache: false
    prefix: classpath:/templates/

---
#spring:
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:tcp://localhost/~/test # http://192.168.176.1:8082/login.do?jsessionid=1be0d5a624d86aa95058fc11f4da0ff4
#    username: sa
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/handey?serverTimezone=Asia/Seoul
    username: root
    password: 9999

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        formal_sql: true

#    <filter>
#      <filter-name>logFilter</filter-name>
#      <filter-class>com.kh.swith.common.filter.LogFilter</filter-class>
#    </filter>
#    <filter-mapping>
#      <filter-name>logFilter</filter-name>
#      <url-pattern>/*</url-pattern>
#    </filter-mapping>