spring:
  devtools:
    livereload:
      enabled: true
  freemarker:
    cache: false    #    실서버 배포시에는 이 옵션을 개발서버와 실서버용으로 분리시켜야 한다. 템플릿을 캐시하지 않으면 서버 터지는걸 볼 수 있다. https://jojoldu.tistory.com/48
  thymeleaf:
    cache: false
    prefix: classpath:/templates/

---
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/handeytest # http://192.168.176.1:8082/login.jsp?jsessionid=e127821955429388dd0b6ffcb3046acf
    username: sa