drop table if exists todo_box CASCADE;
create table todo_box
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY,
    title varchar(255),
    index bigint default 1,
    fixed boolean default 0,
    user_id bigint not null,
    primary key (id),
    foreign key (user_id) references join_mem(id) on delete cascade
);

drop table if exists todo_elm CASCADE;
create table todo_elm
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY,
    content varchar(255),
    completed boolean default 0,
    to_do_box_id bigint not null,
    primary key (id),
    foreign key (to_do_box_id) references todo_box(id) on delete cascade
);

drop table if exists weekly_box CASCADE;
create table weekly_box
(
    id bigint generated by default as identity,
    title varchar(255),
    index bigint default 0,
    user_id bigint not null,
    primary key (id),
    foreign key (user_id) references join_mem(id) on delete cascade
);

drop table if exists weekly_elm CASCADE;
create table weekly_elm
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY,
    content varchar(255),
    completed boolean default 0,
    weekly_box_id bigint not null,
    primary key (id),
    foreign key (weekly_box_id) references weekly_box(id) on delete cascade
);

drop table if exists join_mem CASCADE;
create table join_mem
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY,
    username varchar(255),
    email varchar(255),
    password varchar(255),
    primary key(id)
);


drop table if exists memo CASCADE;
create table memo
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY,
    content varchar(2000),
    user_id bigint not null,
    primary key (id),
    foreign key (user_id) references join_mem(id) on delete cascade
);

drop table if exists todo_box_hst CASCADE;
create table todo_box_hst
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY,
    title varchar(255),
    saveDt date,
    user_id bigint not null,
    primary key (id),
    foreign key (user_id) references join_mem(id) on delete cascade
);

drop table if exists todo_elm_hst CASCADE;
create table todo_elm_hst
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY,
    content varchar(255),
    completed boolean default 0,
    todo_box_hst_id bigint not null,
    primary key (id),
    foreign key (todo_box_hst_id) references todo_box_hst(id) on delete cascade
);

drop table if exists after_history CASCADE;
create table after_history
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY,
    content varchar(255),
    hist_date date,
    user_id bigint not null,
    primary key (id),
    foreign key (user_id) references join_mem(id) on delete cascade
);


drop table if exists trash_box CASCADE;
create table trash_box
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY,
    title varchar(255),
    notitle boolean,
    registerDt date,
    endDt date,
    user_id bigint not null,
    primary key (id),
    foreign key (user_id) references join_mem(id) on delete cascade
);

drop table if exists trash_elm CASCADE;
create table trash_elm
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY,
    content varchar(255),
    completed boolean,
    trash_box_id bigint not null,
    primary key (id),
    foreign key (trash_box_id) references trash_box(id) on delete cascade
);

drop table if exists user_info CASCADE;
create table user_info
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY,
    reset_time varchar(2) default '0',
    user_id bigint not null,
    primary key (id),
    foreign key (user_id) references join_mem(id) on delete cascade
);

drop table if exists auth CASCADE;
create table auth
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY,
    refresh_token varchar(1000),
    user_id bigint not null,
    primary key (id),
    foreign key (user_id) references join_mem(id) on delete cascade
);

drop table if exists schedule CASCADE;
create table schedule
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY,
    content varchar(255),
    start_dt datetime,
    end_dt datetime,
    user_id bigint not null,
    primary key (id),
    foreign key (user_id) references join_mem(id) on delete cascade
);

drop table if exists fw_box CASCADE;
create table fw_box
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY,
    title varchar(255),
    saveDt date,
    weekly_box_id bigint,
    user_id bigint not null,
    primary key (id),
    foreign key (user_id) references join_mem(id) on delete cascade,
    foreign key (weekly_box_id) references weekly_box(id) on delete set null
);

drop table if exists fw_elm CASCADE;
create table fw_elm
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY,
    content varchar(255),
    fw_box_id bigint not null,
    weekly_elm_id bigint,
    primary key (id),
    foreign key (fw_box_id) references fw_box(id) on delete cascade,
    foreign key (weekly_elm_id) references weekly_elm(id) on delete set null
);